In [2]:
import numpy as np
import pandas as pd

exam = ({
    'Noms':('Anastasia', ('Dima'), ('Katherine'), ('James'), ('Emily'), ('Michael'), ('Matthieu'), ('Laura'), ('Kevin'), ('Jonas')),
    'Scores' : (12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19),
    'Tentatives' : (1, 3, 2, 3, 2, 3, 1, 1, 2, 1),
    'Qualifier' : (['oui', 'non', 'oui', 'non', 'non', 'oui', 'oui', 'non', 'non', 'oui'])
})

etiq = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam, index = etiq)
print("\n---:le score de chaque joueur:---")
print("\n",df)
df1 = df.head(3)
print("\n---: 1.voici les 3 premières lignes du dictionnaire:---\n")
print(df1)
print("\n---: 2.Suppression des lignes avec des valeurs NaN : ---")
print(df.dropna())
print("\n---: 3. Extraire les colonnes 'Noms' et 'Scores' : ---")
print("\n",df[["Noms","Scores"]])
#indexis = ['k']
#nv_lig = pd.DataFrame([["Sureh", 15.5, 1, "Oui"]], columns = df.columns, index = indexis)
#print("\n",nv_lig)
#df = df.append(nv_lig, ignore_index=True, sort=True)
# la methode .loc() nous permet d'ajouter une ligne avec son index dans le tableau
df.loc['k'] = ["Sureh", 15.5, 1, "Oui"]
print("\n---:4. La Nouvelle ligne k à ajouter est :")
print("\n",df)
print("\n---: 5. la colonne 'Tentatives' est supprimée : ---")
print("\n",df.drop(["Tentatives"], axis = 1))
print("\n------6 .Ajout d'une nouvelle colonne succès, si le score est spérieur à 10---on a 1 ---sinon---on a 0 \n")
df ['Succès'] = np.where(df['Scores'] > 10, '1', '0')
#df['Succès'] = ['bon' if s > 10 else "mauvais" for s in df['Scores'] ]
print(df)

---:le score de chaque joueur:---

         Noms  Scores  Tentatives Qualifier
a  Anastasia    12.5           1       oui
b       Dima     9.0           3       non
c  Katherine    16.5           2       oui
d      James     NaN           3       non
e      Emily     9.0           2       non
f    Michael    20.0           3       oui
g   Matthieu    14.5           1       oui
h      Laura     NaN           1       non
i      Kevin     8.0           2       non
j      Jonas    19.0           1       oui

---: 1.voici les 3 premières lignes du dictionnaire:---

        Noms  Scores  Tentatives Qualifier
a  Anastasia    12.5           1       oui
b       Dima     9.0           3       non
c  Katherine    16.5           2       oui

---: 2.Suppression des lignes avec des valeurs NaN : ---
        Noms  Scores  Tentatives Qualifier
a  Anastasia    12.5           1       oui
b       Dima     9.0           3       non
c  Katherine    16.5           2       oui
e      Emily     9.0           2       non
f    Michael    20.0           3       oui
g   Matthieu    14.5           1       oui
i      Kevin     8.0           2       non
j      Jonas    19.0           1       oui

---: 3. Extraire les colonnes 'Noms' et 'Scores' : ---

         Noms  Scores
a  Anastasia    12.5
b       Dima     9.0
c  Katherine    16.5
d      James     NaN
e      Emily     9.0
f    Michael    20.0
g   Matthieu    14.5
h      Laura     NaN
i      Kevin     8.0
j      Jonas    19.0

---:4. La Nouvelle ligne k à ajouter est :

         Noms  Scores  Tentatives Qualifier
a  Anastasia    12.5           1       oui
b       Dima     9.0           3       non
c  Katherine    16.5           2       oui
d      James     NaN           3       non
e      Emily     9.0           2       non
f    Michael    20.0           3       oui
g   Matthieu    14.5           1       oui
h      Laura     NaN           1       non
i      Kevin     8.0           2       non
j      Jonas    19.0           1       oui
k      Sureh    15.5           1       Oui

---: 5. la colonne 'Tentatives' est supprimée : ---

         Noms  Scores Qualifier
a  Anastasia    12.5       oui
b       Dima     9.0       non
c  Katherine    16.5       oui
d      James     NaN       non
e      Emily     9.0       non
f    Michael    20.0       oui
g   Matthieu    14.5       oui
h      Laura     NaN       non
i      Kevin     8.0       non
j      Jonas    19.0       oui
k      Sureh    15.5       Oui

------6 .Ajout d'une nouvelle colonne succès, si le score est spérieur à 10---on a 1 ---sinon---on a 0

        Noms  Scores  Tentatives Qualifier Succès
a  Anastasia    12.5           1       oui      1
b       Dima     9.0           3       non      0
c  Katherine    16.5           2       oui      1
d      James     NaN           3       non      0
e      Emily     9.0           2       non      0
f    Michael    20.0           3       oui      1
g   Matthieu    14.5           1       oui      1
h      Laura     NaN           1       non      0
i      Kevin     8.0           2       non      0
j      Jonas    19.0           1       oui      1
k      Sureh    15.5           1       Oui      1